### ISSUE TITLE
error[E0658]: `c".."` literals are experimental

### ISSUE THREAD

**Issue by davidlougheed** [jguhlin/minimap2-rs#106]
I'm trying to build minimap2 using Rust 1.76.0, which historically was working, but now gives the aforementioned `error[E0658]: `c".."` literals are experimental` error in several places, e.g.:

```
error[E0658]: `c".."` literals are experimental
   --> /home/dlough2/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minimap2-0.1.22+minimap2.2.28/src/lib.rs:110:22
    |
110 | static CDNA: &CStr = c"cdna";
    |                      ^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable
```

**Comment by jguhlin** [comment]
I can change it back if absolutely necessary, but can you upgrade to a more stable rust? That should let it work

**Comment by davidlougheed** [comment]
I'll just revert the versions manually to 0.1.20 for minimap2-rs and 0.1.19 for minimap2-sys. This is the latest version of Rust I have access to on my university's cluster.

**Comment by jguhlin** [comment]
Ok, let me know if it's too much of a problem and I can revert. Especially if you run into any crashes. It's just a bit more readable on my end.

You could also try to install a local rust with rustup? then it's just in your home directory and you can switch versions around? That's what I do on the HPCs here, heh
