### ISSUE TITLE
Use minimap2 version number

### ISSUE THREAD

**Issue by alexomics** [jguhlin/minimap2-rs#29]
Would it be possible for the `minimap2-sys` crate to follow the version number scheme that https://github.com/lh3/minimap2 uses?

This will make it easier for downstream tools to know what features are available.

**Comment by jguhlin** [comment]
Would something like how zstd handles it work?
So the version number would be similar to "0.12.3+zstd.1.5.2"

For mm2-fast (and if any other backends) I'll just leave the version number in the docs somewhere.
