### ISSUE TITLE
compiling on macOS

### ISSUE THREAD

**Issue by scfurl** [jguhlin/minimap2-rs#30]
Hi @jguhlin,

Thanks for all your work on minimap2-rs!  I am working on a rust project that would be ideal for minimap2 bindings.  I have successfully integrated into my project in a linux environment, but compiling fails on a Mac.  I suspect that it is related to SSE4 code that I need to disable when successfully building minimap2 on a Mac using `make sse2only=1`.  I see you have related tasks in your todo list.  Have you gotten minimap2-rs to specifically compile on an ARM Mac?  Could you share the trick? :)  Or do you think something else is causing compilation failure?

Thanks for looking!!

I have output the compilation errors when running ` cargo build --release` below:

   Compiling minimap2-sys v0.1.10
   Compiling seq_io v0.3.1
   Compiling csv v1.2.1
   Compiling itertools v0.10.5
   Compiling toml v0.5.11
The following warnings were emitted during compilation:

warning: clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
warning: clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
warning: In file included from minimap2/ksw2_ll_sse.c:9:
warning: In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/emmintrin.h:13:
warning: In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/xmmintrin.h:13:
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:50:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:129:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:159:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:189:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:216:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:239:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:260:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:287:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:310:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:331:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:352:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:373:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:394:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:416:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:439:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:461:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:483:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_paddusw((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:504:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_psubb((__v8qi)__m1, (__v8qi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:525:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
warning:     return (__m64)__builtin_ia32_psubw((__v4hi)__m1, (__v4hi)__m2);
warning:            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: fatal error: too many errors emitted, stopping now [-ferror-limit=]
warning: 20 errors generated.

error: failed to run custom build command for `minimap2-sys v0.1.10`

**Comment by jguhlin** [comment]
Trying to find a CircleCI config that lets me test mac compilation. I can try and add a feature for sse1only, but for now, can you try simde?

cargo build --release --features simde ?

**Comment by scfurl** [comment]
Hmm.  Maybe I am missing something?

`cargo build --release --features simde
error: none of the selected packages contains these features: simde`

**Comment by jguhlin** [comment]
Are you running the compilation from your own project? You'll have to set up the features in Cargo.toml
Otherwise, if you are using the github version maybe do a new pull?

**Comment by scfurl** [comment]
Yes, I was...  And I can confirm that a clone of the minimap2-rs repo will compile fine if I use the `--features side` flag, but not without it.

So I guess I need to figure out how to have my project recognize the architecture and compile minimap2-rs appropriately.  I tried just putting this in my Cargo.toml file, but it didn't work 

`minimap2 = { version = "0.1.11", default-features = false, features = ["simde"] }`

(I realize this is now outside the scope of the question so I will close this, but any help would be greatly appreciated)!!

thank you

**Comment by jguhlin** [comment]
You can leave this open if you'd like. SIMDe is SIMD-everywhere, so you should be good with it always on.

Looks like there is no option yet for per-target features: https://github.com/rust-lang/cargo/issues/1197

**Comment by scfurl** [comment]
Thanks for clarifying!  So including this in my project should technically work everywhere right?  But it still doesn't compile on Mac...  

```sh
[dependencies]
minimap2-sys = { version = "0.1.10", features = ["simde"] }
minimap2 = "0.1.11"
```

**Comment by jguhlin** [comment]
Do you need minimap2-sys? If not, you can use 

minimap2 = { version = "0.1.11", features = ["simde"] }

**Comment by scfurl** [comment]
Unfortunately that doesn't work either...

**Comment by jguhlin** [comment]
Hmm, thanks for that. What about a cargo clean, then try again?

Otherwise, that's helpful info; I need to get a way to test mac builds automatically!

**Comment by scfurl** [comment]
Same result after clean and retry :(

**Comment by jguhlin** [comment]
Ok thanks for that. I've got some meetings right now but will try to get to this later today / tomorrow and reach back to you!

**Comment by jguhlin** [comment]
Still working on this, been busy! Any luck on your end?

**Comment by jguhlin** [comment]
It took me way too long to get Github actions to test on MacOS, but it's working now, so once that's finished I'll push this release out.

**Comment by Adoni5** [comment]
@jguhlin - did you find a way of testing GitHUb actions for this on Arm based architectures for MacOS? We're having issues compiling `mappy-rs` on M1/M2 Macs on arm, and have to use x86 emulation. 

Unfortunately I'm a linux lover, and have no access to an Arm based CPU, so would be great if I could find an environment to test in!

**Comment by jguhlin** [comment]
@Adoni5 Hmm, it compiles on macos with the latest github workflow, but I think that runs on x86_64. I'm trying cross (https://github.com/cross-rs/cross) now, but under wsl2. It won't do aarch64 + macos but I guess if they are tested independently, it may work?

My work machine's ubuntu install has died during an upgrade. I'm going in on Monday with a gentoo install, but it puts me behind a bit. :/

**Comment by jguhlin** [comment]
Froze on building tokio on my machine, will have to try on Monday.

**Comment by jguhlin** [comment]
@scfurl @Adoni5 New version is out, I can build on aarch64 but the cfg flags do not properly propagate for my cross compilation. Can you give it a try?

**Comment by jguhlin** [comment]
Hey thanks. Could you post your error logs?

**Comment by leiste375** [comment]
> Hey thanks. Could you post your error logs?

The error messages were exactly the same as encountered by @scfurl. Without simde the one at the top, and with simde the one further below (Undefined symbols for architecture arm64...).

I also tried loading the crate directly via GitHub. When doing so I have to manually turn default-features off and separately specify flate2 (in the chopper .toml) in addition to simde (as a feature of minimap2), only to end up at the latter error message (Undefined symbols...).

**Comment by jguhlin** [comment]
Cool thanks. Good to know. I'll dig into it more next week. Cheers

**Comment by jguhlin** [comment]
@leiste375 I think it's the build.rs not taking in the proper options. I've sorted a mac to borrow for a few weeks to get it sorted (hopefully it takes an afternoon!). It's my first FFI project so am surprised it has worked this well even.

**Comment by jguhlin** [comment]
I did not get an aarch64 mac to test on. :/ Still trying.

**Comment by Adoni5** [comment]
Thanks @jguhlin - I'll have a think and see what I can do as well.

**Comment by leiste375** [comment]
> I did not get an aarch64 mac to test on. :/ Still trying.

Let me know if there is anything I can try from my end. I hope I'll find time to look at it again soon

**Comment by leiste375** [comment]
Managed to compile. Will test it and create a pull request later on if that's ok with you

**Comment by Adoni5** [comment]
🔥 Thanks @leiste375
