### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by 70m43** [jguhlin/minimap2-rs#47]
Hi thank you for your work.

This example code gives me ```[]``` as output

```
use minimap2::Aligner;
use std::path::Path;

fn main() {
    let ref_path = "/home/thomas/NGS/ref/hg19.fa";

    let mut aligner = Aligner::builder()
        .map_ont()
        .with_threads(8)
        .with_cigar()
        .with_index(ref_path, None)
        .expect("Unable to build index");

    let seq: Vec<u8> = b"ACTGACTCACATCGACTACGACTACTAGACACTAGACTATCGACTACTGACATCGA".to_vec();
    let alignment = aligner
        .map(&seq, false, false, None, None)
        .expect("Unable to align");
    println!("{:?}", alignment);
}
```

my Toml configuration is :
```
[package]
name = "desc_seq_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimap2 = "0.1.16+minimap2.2.26"
```

cargo 1.74.0-nightly (d5336f813 2023-09-14)

**Comment by jguhlin** [comment]
Ah, that's the example in the docs. My fault. For such a short sequence you'll need .short() or .sr() instead of .map_ont().

**Comment by 70m43** [comment]
Thank you but neither changing for .short() nor .sr() nor a longer sequence solve the issue.

**Comment by 70m43** [comment]
It's the same with the sequence from ```samtools faidx /home/thomas/NGS/ref/hg19.fa chr17:18573597-18573711"

**Comment by 70m43** [comment]
I removed ```with_cigar()``` and no it works...

**Comment by jianshu93** [comment]
Hello All, 

Is this problem solved? I do need Cigar for calculating identities, but the default PAF also works for me. Just wonder whether the Cigar functionality also works.

Thanks,

Jianshu
