### ISSUE TITLE
FEATURE: Make work with rayon

### ISSUE THREAD

**Issue by jguhlin** [jguhlin/minimap2-rs#5]

**Comment by Ge0rges** [comment]
Hello,

I was wondering if there was any update to this issue?

**Comment by jguhlin** [comment]
@Ge0rges No, I haven't thought about it in awhile, but I could revisit it soon. The best way to use multiple threads is as shown in the example program (fakeminimap2) using a worker queue system. It has to do with the send + sync traits with the minimap2 FFI. I would like to get there eventually though.

**Comment by jguhlin** [comment]
You made it work @Ge0rges , can you give it some more tests?

**Comment by Ge0rges** [comment]
I think it works!

**Comment by jguhlin** [comment]
Awesome! I'll keep it as "experimental" for now and if nobody has any major issues I'll mark it as stable next release or so.

**Comment by jguhlin** [comment]
Rayon works
