### ISSUE TITLE
rayon parallelization

### ISSUE THREAD

**Issue by jianshu93** [jguhlin/minimap2-rs#56]
hello @jguhlin,

I have a bunch of sequences, each sequence has some reference sequences to align against (different for each sequence), I saw the fakeminimap2 for parallelizing when sequences share the share reference. But in this case, they do not share the same references, how would you suggest to do parallelize, I have a million such sequences. 

Thanks,

Jianshu

**Comment by jguhlin** [comment]
Hey. You'll just have to make a new mapper instance for each reference sequence, then do all the queries against that. 

I still like the channel system, but I believe rayon works now?
