### ISSUE TITLE
Update minimap2-sys to minimap2 2.28

### ISSUE THREAD

**Issue by Adoni5** [jguhlin/minimap2-rs#58]
Hey @jguhlin,

Long time! I was wondering if you could update the minimap2-sys bindings to 2.28, I'm into that lrhq preset.
I'll have a crack at it and put a PR at some point, but I'm deep in the writing up bush, so I'm not sure when that might be!

Thanks,
Rory

**Comment by jguhlin** [comment]
Hey! Yeah definitely. lrhq is in 2.27 but I must have missed 2.28's release. I'll work on that in the next day or two.

**Comment by jguhlin** [comment]
All tests were successful on my system, should be on crates.io now!

**Comment by Adoni5** [comment]
Thanks dude!
