### ISSUE TITLE
open syncmer version of minimap2?

### ISSUE THREAD

**Issue by jianshu93** [jguhlin/minimap2-rs#60]
Dear @jguhlin,

I think there is a open syncmer (not minimzer) as seed (https://github.com/lh3/minimap2/blob/c2f07ff2ac8bdc5c6768e63191e614ea9012bd5d/sketch.c#L145-L192), but not sure whether the rust version provided the interface to use it.

Thanks,

Jianshu

**Comment by jguhlin** [comment]
It should be possible to pull that version as a submodule and rebuild minimap2-sys and use the low-level bindings to get it. I'll see if I can incorporate it later this week.

**Comment by jguhlin** [comment]
I wasn't able to get this working, but if you want to give it a go feel free to open a PR.
