### ISSUE TITLE
Question: Minimap2 Alignment options

### ISSUE THREAD

**Issue by Sam-Sims** [jguhlin/minimap2-rs#70]
Hello! Nice crate,

It would be nice to have the ability to build the minimap2 alignment options (i.e `--score-N`) in the same way the MapOpts or IdxOpts are currently implemented. I can see some of the alignment options in MapOpts - I think matching score, `-A`,  and Gap open penalty, `-O`, Is `--score-N` supported? 

Likewise for Input/Output options - for example id like to be able to exclude secondary alignments (in minimap2 thats `--secondary=yes|no`)

Might be missing something obvious.

Thanks!

**Comment by jguhlin** [comment]
Not missing anything obvious, everything is added on an as-needed basis! I'll look at adding more options to the Aligner builder-style, in line with how map opts and idx opts are handled now. If you've got important ones you need now, let me know, and I can prioritize, or feel free to open a PR.

**Comment by jguhlin** [comment]
@Sam-Sims Planning to push a release out in the next week, are there any options you'd like to be brought out right now to the builder pattern?

**Comment by Sam-Sims** [comment]
Hi @jguhlin the only option I wanted to use, but I couldnt easily find was the gap open penalty (-O in minimap2). It might be nice to add to the documentation the equivlent minimap2 CLI flag so its clearer what each opt does. similar to the comments the minimap2 code - e.g https://github.com/lh3/minimap2/blob/618d33515e5853c4576d5a3d126fdcda28f0e8a4/main.c#L208

Granted you can cross reference this with minimap2 code (like the above link) so maybe just me being more familar with the minimap2 CLI.

Thanks!

**Comment by jguhlin** [comment]
@Sam-Sims I've added some documentation about which fields map to which options in minimap2, and how to apply flags. But, if you do use stuff frequently, let me know. `.with_cigar()` looks better to me than `aligner.mapopt.flag |= MM_F_CIGAR as i64;`

But also, if it's rarely used, probably not worth cluttering up the interface.
