### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by jianshu93** [jguhlin/minimap2-rs#8]
Hello Team,

Does it compile on Linux or MacOS, I cannot compile both by runnning cargo build --release after clone minimap2 under minimap2-sys folder:

The following warnings were emitted during compilation:

warning: minimap2/hit.c: In function 'mm_gen_regs':
warning: minimap2/hit.c:74:18: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
warning:    74 |  r = (mm_reg1_t*)calloc(n_u, sizeof(mm_reg1_t));
warning:       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: In file included from /usr/include/bits/string2.h:1296,
warning:                  from /usr/include/string.h:633,
warning:                  from minimap2/hit.c:1:
warning: /usr/include/stdlib.h:467:14: note: in a call to allocation function 'calloc' declared here
warning:   467 | extern void *calloc (size_t __nmemb, size_t __size)
warning:       |              ^~~~~~

error: failed to run custom build command for `minimap2-sys v0.1.6`

Caused by:
  process didn't exit successfully: `/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-81c7d28179994891/build-script-build` (exit status: 101)
  --- stdout
  "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out"
  cargo:rerun-if-changed=minimap2/*.c
  cargo:rerun-if-env-changed=ZLIB_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ZLIB_STATIC
  cargo:rerun-if-env-changed=ZLIB_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SYSROOT
  cargo:rerun-if-env-changed=ZLIB_STATIC
  cargo:rerun-if-env-changed=ZLIB_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rustc-link-search=native=/usr/lib64
  cargo:rustc-link-lib=z
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ZLIB_STATIC
  cargo:rerun-if-env-changed=ZLIB_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rustc-link-lib=m
  cargo:rustc-link-lib=pthread
  Compiling...
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/align.o" "-c" "minimap2/align.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/bseq.o" "-c" "minimap2/bseq.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/esterr.o" "-c" "minimap2/esterr.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/format.o" "-c" "minimap2/format.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/hit.o" "-c" "minimap2/hit.c"
  cargo:warning=minimap2/hit.c: In function 'mm_gen_regs':
  cargo:warning=minimap2/hit.c:74:18: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  cargo:warning=   74 |  r = (mm_reg1_t*)calloc(n_u, sizeof(mm_reg1_t));
  cargo:warning=      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/include/bits/string2.h:1296,
  cargo:warning=                 from /usr/include/string.h:633,
  cargo:warning=                 from minimap2/hit.c:1:
  cargo:warning=/usr/include/stdlib.h:467:14: note: in a call to allocation function 'calloc' declared here
  cargo:warning=  467 | extern void *calloc (size_t __nmemb, size_t __size)
  cargo:warning=      |              ^~~~~~
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/index.o" "-c" "minimap2/index.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/kalloc.o" "-c" "minimap2/kalloc.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_dispatch.o" "-c" "minimap2/ksw2_dispatch.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_extd2_sse.o" "-c" "minimap2/ksw2_extd2_sse.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_exts2_sse.o" "-c" "minimap2/ksw2_exts2_sse.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_extz2_sse.o" "-c" "minimap2/ksw2_extz2_sse.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_ll_sse.o" "-c" "minimap2/ksw2_ll_sse.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/kthread.o" "-c" "minimap2/kthread.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/lchain.o" "-c" "minimap2/lchain.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/map.o" "-c" "minimap2/map.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/misc.o" "-c" "minimap2/misc.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/options.o" "-c" "minimap2/options.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/pe.o" "-c" "minimap2/pe.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/sdust.o" "-c" "minimap2/sdust.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/seed.o" "-c" "minimap2/seed.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/sketch.o" "-c" "minimap2/sketch.c"
  exit status: 0
  running: "/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-o57x6h2gubo7bzh7evmy4mvibdqrlghr/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-I" "minimap2" "-DHAVE_KALLOC" "-O2" "-lm" "-lz" "-lpthread" "-o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/splitidx.o" "-c" "minimap2/splitidx.c"
  exit status: 0
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  running: "ar" "cq" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/liblibminimap.a" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/align.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/bseq.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/esterr.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/format.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/hit.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/index.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/kalloc.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_dispatch.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_extd2_sse.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_exts2_sse.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_extz2_sse.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/ksw2_ll_sse.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/kthread.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/lchain.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/map.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/misc.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/options.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/pe.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/sdust.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/seed.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/sketch.o" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/minimap2/splitidx.o"
  exit status: 0
  running: "ar" "s" "/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out/liblibminimap.a"
  exit status: 0
  cargo:rustc-link-lib=static=libminimap
  cargo:rustc-link-search=native=/storage/coda1/p-ktk3/0/jzhao399/rich_project_bio-konstantinidis/apps/minimap2-rs/target/release/build/minimap2-sys-a98d8c2a6b240956/out
  Compiled!

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', /storage/home/hcoda1/4/jzhao399/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.61.0/./lib.rs:2276:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thanks,

Jianshu

**Comment by jguhlin** [comment]
Looks like you may be missing clang. Please try installing as appropriate here and let me know if that works:

https://rust-lang.github.io/rust-bindgen/requirements.html

I also recommend using it from crates.io rather than compiling from source, but let me know how it goes whichever you decide to do. Cheers

**Comment by jianshu93** [comment]
now I can confirm that it compiles.


Many thanks,

Jianshu
