### ISSUE TITLE
Invalid cast (on arm64?)

### ISSUE THREAD

**Issue by rob-p** [jguhlin/minimap2-rs#82]
Within minimap2-rs, I'm getting [the following error](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/126266/workflows/797d75f4-c39a-4b40-9135-2e867aaeb2de/jobs/204317?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-107-531504_105) when building on bioconda for an arm64 linux machine:

```
19:11:58 BIOCONDA INFO (OUT)     |
19:11:58 BIOCONDA INFO (OUT) 856 |                         self.idx.as_ref().unwrap() as *const mm_idx_t,
19:11:58 BIOCONDA INFO (OUT)     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:11:58 BIOCONDA INFO (OUT) 
19:11:58 BIOCONDA INFO (OUT) error[E0606]: casting `&*mut minimap2_sys::mm_idx_t` as `*const minimap2_sys::mm_idx_t` is invalid
19:11:58 BIOCONDA INFO (OUT)    --> /opt/conda/conda-bld/oarfish_1724699349146/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minimap2-temp-0.1.30+minimap2.2.28/src/lib.rs:998:41
```

I'm looking into why this is not valid and what the alternative should be.

**Comment by rob-p** [comment]
I made the code for these casts in these branches match those in the other cfg branches and this solved the issue (it compiles at least).  I’ll update my pending PR accordingly.

**Comment by jguhlin** [comment]
Awesome. Sorry I've been hit with some bad migrane or something so am really slow right now.

**Comment by jguhlin** [comment]
Build and test work for me with 
```
cross test --target aarch64-unknown-linux-gnu
```

Can you check on your end if the current branch is building for you?

**Comment by jguhlin** [comment]
This should be working now. Re-open if not
