### ISSUE TITLE
When will version 0.1.21 be released?

### ISSUE THREAD

**Issue by keithyin** [jguhlin/minimap2-rs#83]
When will version 0.1.21 be released? I found that version 0.1.20 still has the bug with cigar_str. But the bug has been fixed at main branch.

version 0.1.20. src/lib.rs:941
`
cigar_str = format!("{}{}{}", clip_len0, cigar_str, clip_char);
`

**Comment by jguhlin** [comment]
Getting close!

**Comment by jguhlin** [comment]
@keithyin It's released!

**Comment by mbhall88** [comment]
I wonder if you would consider keeping a changelog and tagging releases @jguhlin? 

That would make it much easier for consumers of the library to be notified about when a new release is out, and what has changed.

**Comment by jguhlin** [comment]
Changelog is at the bottom of the notes. I'll put them in a markdown file
if that'll help. I should start tagging releases. It was kind of cursed
with github actions before but I think it's fixed now.

**Comment by mbhall88** [comment]
Ooops my bad, didn't see it at the bottom of the README. Yeah, maybe a separate file would be a little more conventional. But I don't want to tell you how to organise your repo so feel free to leave it there and I will just use my eyes better next time 😅

**Comment by jguhlin** [comment]
All good. It was such a small project before you didn't even need to
scroll! Growing pains haha
