### ISSUE TITLE
Order of chain on Aligner::builder() matters for .with_cigar

### ISSUE THREAD

**Issue by wdecoster** [jguhlin/minimap2-rs#84]
This was unexpected, at least for me, and I don't know if this is a bug but I just wanted to leave this here for if others stumble upon the same...

The first code block below will result in an aligner that does _not_ create an Alignment, despite the .with_cigar

```rust
let aligner = Aligner::builder()
    .map_ont()
    .with_cigar()
    .splice()
    .with_index_threads(8)
    .with_index("ref.fa", None)
    .expect("Unable to build minimap2 index from reference genome");
```

But it works as expected if you change the order of the builder:

```rust
let aligner = Aligner::builder()
    .map_ont()
    .splice()
    .with_cigar()
    .with_index_threads(8)
    .with_index("ref.fa", None)
    .expect("Unable to build minimap2 index from reference genome");
```

Best,
Wouter

**Comment by jguhlin** [comment]
Splice and map_ont are two different presets, so each will reset the whole configuration back to default. Could add in some checks to make sure two can't be used?
