### ISSUE TITLE
FEATURE: Remove bindgen requirement from regular builds

### ISSUE THREAD

**Issue by jguhlin** [jguhlin/minimap2-rs#9]
This would fix #8.

**Comment by jianshu93** [comment]
Hello, 

I am wondering how exactly you remove the dependency on libclang? We have another binding called hmmer-rs but relies on libclang.


Thanks,

Jianshu

**Comment by jguhlin** [comment]
@jianshu93 Hey, apologies for the delay. To remove libclang you need to copy the compiled bindings.rs into the src folder, and use that unless a bindgen feature flag is enabled.

See here: https://github.com/jguhlin/minimap2-rs/blob/main/minimap2-sys/src/lib.rs#L5

Make bindgen optional and a feature flag:
https://github.com/jguhlin/minimap2-rs/blob/main/minimap2-sys/Cargo.toml#L42

And the same in your build.rs script.

https://github.com/jguhlin/minimap2-rs/blob/main/minimap2-sys/build.rs#L181

And that should handle it.

**Comment by jianshu93** [comment]
Thanks！

I will try and let you know.

Thanks

Jianshu
